eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.10.252:8761/eureka/

spring:
  application:
    name: businessService-feign
  redis:
    database: 0
    host: r-2zej846k1uky4mwvt8.redis.rds.aliyuncs.com
    port: 6379
    password:
    jedis:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 4
  redispre:
    value: "cnrmall:cache:"
  tokenpre:
    value: "token:"
  session:
    store-type: redis
  #cloud:
    #nacos:
      #discovery:
        #server-addr: 172.17.10.252:8848

service:
  server:
    address: http://service-provider/
    #membercenter: http://member-center/