spring:
  application:
    name: service-feign-prod
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 4
  redispre:
    value: "auction:cache:"
  tokenpre:
    value: "token:"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service:
  server:
    address: http://service-provider-prod/
    user: http://user-center-prod/
